# go-gateway/Dockerfile
FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# build binary
RUN go build -o gateway main.go

# --- runtime image ---
FROM alpine:3.20
WORKDIR /app

# copy binary and example.env
COPY --from=builder /app/gateway .
COPY example.security /app/security
COPY example.env /app/.env

EXPOSE 8080
CMD ["./gateway"]

