
# Stage 1: Build
FROM rust:1.91-slim  AS builder
WORKDIR /app

# Enable edition 2024
ENV RUST_EDITION=2024

# Copy workspace files
COPY Cargo.toml Cargo.lock ./
COPY domain domain
COPY infrastructure infrastructure
COPY interface interface
COPY application application
COPY utils utils
COPY security security
COPY migrations migrations

# install sqlx for seed db 
RUN cargo install sqlx-cli --no-default-features --features postgres,rustls
# Build with release optimization
RUN cargo build --release --locked

# Stage 2: Runtime
FROM ubuntu:24.04
WORKDIR /app

# install minimal libs (openssl/sqlx)
RUN apt-get update && apt-get install -y \
    libssl3 ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# copy binary
COPY --from=builder /app/target/release/app_service /usr/local/bin/app_service
COPY --from=builder /usr/local/cargo/bin/sqlx /usr/local/bin/sqlx

# copy env + keys
COPY .env /app/.env
COPY security /app/security
COPY migrations /app/migrations

# default entrypoint
CMD ["/bin/sh","-c","sqlx migrate run && /usr/local/bin/app_service"]

