# ------------------------
# Stage 1: builder
# ------------------------
FROM rust:1.88 AS builder

WORKDIR /app
COPY . .
RUN echo "=== Check edition in container ===" && \
    grep -R "edition" --include Cargo.toml . || true && \
    grep -R "cargo-features" --include Cargo.toml . || true
RUN cat /app/Cargo.toml
# compile release binary
RUN cargo build --release

# ------------------------
# Stage 2: runtime (slim) ------------------------
FROM debian:bookworm-slim

# dependencies เช่น openssl, ca-certificates
RUN apt-get update && apt-get install -y \
    libssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# copy binary from builder
COPY --from=builder /app/target/release/app_service /usr/local/bin/app_service

# .env ถ้าอยากก็ COPY เข้ามาได้ แต่ส่วนใหญ่ใช้ Docker secrets หรือ env ตอน run
# COPY .env /app/.env

EXPOSE 3000
CMD ["app_service"]

