# front/Dockerfile
FROM node:22-alpine AS build

WORKDIR /app

# dependency
COPY package*.json ./
RUN npm install

COPY . .

# build production
RUN npm run build

# nginx serve frontend 
#FROM nginx:1.25-alpine
#COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
